# Generated by Django 4.2 on 2024-10-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_recoveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryrequest',
            name='request_type',
            field=models.CharField(default='forgot_password', max_length=50),
        ),
    ]
